language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: a93840e9505a5adc1acf2b394ae777b63b4b478e
  local_dir: dist
  on:
    branch: master
